### ISSUE TITLE
Connect to two different Qlik Servers (i.e. Dev and Staging) in the same session

### ISSUE THREAD

**Issue by minpsd** [ahaydon/Qlik-Cli-Windows#125] opened 2020-07-09 21:06 UTC
Hello - I have another separate issue that I'm experiencing with Qlik Cli.

Currently, I'm able to connect to Qlik Dev server via Qlik Cli for the purpose of exporting Qlik app (which works great). However, when I tried to connect to another Qlik server (i.e. Qlik Staging) in the same Powershell session using this command:

`Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like 'CN=hostname-staging-CA'} | Connect-Qlik -ComputerName hostname -UserName domain\username -TrustAllCerts `

I would receive this error:
```
Get-ChildItem : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like 'CN= ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Get-ChildItem], WebExcepti
   on
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.GetChildItemCommand
```
I ran `gci cert:\CurrentUser\My | Format-List` to check that client certs from both dev and staging Qlik servers are there (they have the same name 'QlikClient' with respective issuers on mmc). Both of the root certs are there as well.

I also tried the method for multi-site operations from this link https://github.com/ahaydon/Qlik-Cli-Windows/wiki/Advanced-usage but I essentially get the same error even though I specified the correct path to the client certs 

The question is how I do connect to Qlik dev server to export an app then connect to Qlik staging to import the app (that was exported from Dev) in the same session? I was able to do them in separate sessions but we plan to create a job in Jenkins to automate this process.

I really appreciate all your help!

**Comment by Nillth** [comment] 2020-07-10 02:54
Personally, I do not like pipelining the certificates in...
separating the process will allow you to better investigate what certificate is being returned.

based on the comment, 

> "Both of the root certs are there as well"

I would assume that the `Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like 'CN=hostname-staging-CA'}` is returning both the QlikClient and the Root certificate which are then being passed by the pipeline causing the issue you are seeing.

If you adjust the call to include the Subject -eq "CN=QlikClient" it should then return the correct cert

```
$Certificate = Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like 'CN=hostname-staging-CA' -and $_.Subject -eq "CN=QlikClient"} 
Connect-Qlik -ComputerName hostname -UserName domain\username -TrustAllCerts -Certificate $Certificate
```

So regarding your question....
adjusting the first 5 lines should be enough to get you going. 

```
#Specify the App to export
$AppGuid = "ed39d8e6-ab2c-44f0-9ecd-75b89dabfd53"

$StagingServerHostName = "hostname-staging"
$ProdcutionServerHostName = "hostname-production"
$UserName = "domain\username"
#Where to export it to
$ExportFile = "C:\temp\$($AppGuid).qvf"

#Get the Certificates
$StagingCertificate = Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like "$($StagingServerHostName)-CA" -and $_.Subject -eq "CN=QlikClient"} 
$ProductionCertificate = Get-ChildItem -Path cert:CurrentUser\My | where {$_.issuer -like "$($ProdcutionServerHostName)-CA" -and $_.Subject -eq "CN=QlikClient"} 

#Connect to the Dev Environment
Connect-Qlik -ComputerName $StagingServerHostName -UserName $UserName -TrustAllCerts -Certificate $StagingCertificate

#Gather the App Info
$QSAppInfo = Get-QlikApp -id $AppGuid
#Export the App
Export-QlikApp -id $AppGuid -filename $ExportFile

#Connect to the Prod Environment 
Connect-Qlik -ComputerName $ProdcutionServerHostName -UserName $UserName -TrustAllCerts -Certificate $ProductionCertificate
#Import the App
$QSImportedApp = Import-QlikApp -file $ExportFile -name $QSAppInfo.Name 

#Display the Info of the new app
$QSImportedApp

#Remove the Temporary export file
Remove-Item -Path $ExportFile
```

**Comment by minpsd** [comment] 2020-07-10 14:43
I followed your steps, however after I connected to the dev server, I still ran into the same issue that it won't allow me to connect to staging server once it's already connected to dev server. 

To clarify, when I said that that both root certs are there - what I meant is that I imported both root certs via mmc so I verified that it's there in mmc. When I ran `gci cert:\CurrentUser\My | Format-List`, I would get this (I'm only showing partial outputs but the thumbprints are different between the two certs if that helps):
```
Subject      : CN=QlikClient
Issuer       : CN=stagingserver-CA

Subject      : CN=QlikClient
Issuer       : CN=devserver-CA
```

The issue seems to be that once I connect to a server, then I can't connect to the other server in the same session (I would have to essentially reboot my machine). For instance, I tried to connect to staging server first then try to connect to dev server but I couldn't connect to dev server after I successfully connected to staging server. Your suggestion pointed the commands to the correct server but it would not connect once I connected to dev server. 

It seems to me that after I export the app from dev via Qlik Cli, I would need to disconnect from dev within the session and once I'm able to disconnect from dev then I should able to connect to staging server. However, I do not know how to disconnect to a Qlik server via Qlik Cli or even if there is a workaround on this?

Nillth - I really appreciate all your help! I'm very new to Powershell so your codes on setting and passing variables help me tremendously! Thank you!

**Comment by ahaydon** [comment] 2020-07-10 16:16
This looks like it was caused by some recent changes to the core function that calls the APIs, the session is not being cleared properly when establishing a new connection.

For now you should be able to work around it by re-importing the module using `Import-Module Qlik-Cli -Force`, that should clear all the script variables and reset any existing sessions.

**Comment by minpsd** [comment] 2020-07-10 19:34
I see. Re-importing the module seems to work! Thank you so much for your help!

**Comment by ahaydon** [comment] 2020-07-14 07:57
This is now fixed in master branch

**Closed by ahaydon** 2020-07-14 07:57 UTC
Labels: help wanted
