### ISSUE TITLE
Exporting or importing large QlikSense applications fails

### ISSUE THREAD

**Issue by hammamr** [ahaydon/Qlik-Cli-Windows#137] opened 2020-10-26 17:26 UTC
Hello,

When exporting or importing large QlikSense applications I have an error (see below).
The maximum application size that we can import is 2 097 137 KO.

Is it possible to use Qlik-Cli to export / import applications larger than 2 097 137 KO ?

Error message: 

> HTTP Error 411. The request must be chunked or have a content length.
> 
> 
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 

Best Regards
Sidi

**Comment by ahaydon** [comment] 2020-10-28 15:45
Duplicate of #129 

Fixed in v1.20.0 that has just been released.

**Closed by ahaydon** 2020-10-28 15:45 UTC

**Comment by hammamr** [comment] 2020-11-03 14:02
Hello,

The export is OK, but the import still fails with applications larger thant 2 GO.
Is there a fix for theis issue ?

Best Regards.
Sidi
